name: Deploy - Desenvolvimento

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Compilando Maven
      run: mvn -B package -DskipTests --file pom.xml

    - name: Render Deploy Action
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.ServiceIdDev }}
        api-key: ${{ secrets.ApiKeyDev }}


    # - name: Deploy na EC2
    #   run: 
    #       echo "${{SECRETS.KEY_EC2_DEV}}" > private_key && chmod 400 private_key
    #       ssh -o StrictHostKeyChecking=no -i "private_key" ubuntu@ec2-18-215-38-246.compute-1.amazonaws.com "
    #           cd /home/ubuntu/PraticaParte2 && 
    #           git pull origin dev           &&
    #           mvn clean package -DskipTests &&
    #           ../excutar.sh "
              
